// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/google/wire"
	"github.com/mapserver2007/ipat-aggregator/app/controller"
	"github.com/mapserver2007/ipat-aggregator/app/domain/service/aggregation_service"
	"github.com/mapserver2007/ipat-aggregator/app/domain/service/analysis_service"
	"github.com/mapserver2007/ipat-aggregator/app/domain/service/converter"
	"github.com/mapserver2007/ipat-aggregator/app/domain/service/filter_service"
	"github.com/mapserver2007/ipat-aggregator/app/domain/service/master_service"
	"github.com/mapserver2007/ipat-aggregator/app/domain/service/prediction_service"
	"github.com/mapserver2007/ipat-aggregator/app/domain/service/summary_service"
	"github.com/mapserver2007/ipat-aggregator/app/infrastructure"
	"github.com/mapserver2007/ipat-aggregator/app/infrastructure/gateway"
	"github.com/mapserver2007/ipat-aggregator/app/usecase/aggregation_usecase"
	"github.com/mapserver2007/ipat-aggregator/app/usecase/analysis_usecase"
	"github.com/mapserver2007/ipat-aggregator/app/usecase/master_usecase"
	"github.com/mapserver2007/ipat-aggregator/app/usecase/prediction_usecase"
)

// Injectors from wire.go:

func NewMaster() *controller.Master {
	betNumberConverter := master_service.NewBetNumberConverter()
	ticketRepository := infrastructure.NewTicketRepository(betNumberConverter)
	ticket := master_service.NewTicket(ticketRepository)
	netKeibaGateway := gateway.NewNetKeibaGateway()
	raceIdRepository := infrastructure.NewRaceIdRepository(netKeibaGateway)
	raceId := master_service.NewRaceId(raceIdRepository)
	raceRepository := infrastructure.NewRaceRepository(netKeibaGateway)
	raceEntityConverter := converter.NewRaceEntityConverter()
	race := master_service.NewRace(raceRepository, raceEntityConverter)
	jockeyRepository := infrastructure.NewJockeyRepository(netKeibaGateway)
	jockeyEntityConverter := converter.NewJockeyEntityConverter()
	jockey := master_service.NewJockey(jockeyRepository, jockeyEntityConverter)
	oddsRepository := infrastructure.NewOddsRepository(netKeibaGateway)
	oddsEntityConverter := converter.NewOddsEntityConverter()
	placeOdds := master_service.NewPlaceOdds(oddsRepository, oddsEntityConverter)
	trioOdds := master_service.NewTrioOdds(oddsRepository, oddsEntityConverter)
	analysisMarkerRepository := infrastructure.NewAnalysisMarkerRepository()
	analysisMarker := master_service.NewAnalysisMarker(analysisMarkerRepository)
	predictionMarkerRepository := infrastructure.NewPredictionMarkerRepository()
	predictionMarker := master_service.NewPredictionMarker(predictionMarkerRepository)
	master := master_usecase.NewMaster(ticket, raceId, race, jockey, placeOdds, trioOdds, analysisMarker, predictionMarker)
	controllerMaster := controller.NewMaster(master)
	return controllerMaster
}

func NewAggregation() *controller.Aggregation {
	term := summary_service.NewTerm()
	ticket := summary_service.NewTicket()
	class := summary_service.NewClass()
	courseCategory := summary_service.NewCourseCategory()
	distanceCategory := summary_service.NewDistanceCategory()
	raceCourse := summary_service.NewRaceCourse()
	spreadSheetSummaryGateway := gateway.NewSpreadSheetSummaryGateway()
	spreadSheetTicketSummaryGateway := gateway.NewSpreadSheetTicketSummaryGateway()
	spreadSheetListGateway := gateway.NewSpreadSheetListGateway()
	spreadSheetAnalysisPlaceGateway := gateway.NewSpreadSheetAnalysisPlaceGateway()
	spreadSheetPredictionGateway := gateway.NewSpreadSheetPredictionGateway()
	spreadSheetRepository := infrastructure.NewSpreadSheetRepository(spreadSheetSummaryGateway, spreadSheetTicketSummaryGateway, spreadSheetListGateway, spreadSheetAnalysisPlaceGateway, spreadSheetPredictionGateway)
	summary := aggregation_service.NewSummary(term, ticket, class, courseCategory, distanceCategory, raceCourse, spreadSheetRepository)
	aggregation_usecaseSummary := aggregation_usecase.NewSummary(summary)
	ticketSummary := aggregation_service.NewTicketSummary(term, spreadSheetRepository)
	aggregation_usecaseTicketSummary := aggregation_usecase.NewTicketSummary(ticketSummary)
	raceEntityConverter := converter.NewRaceEntityConverter()
	jockeyEntityConverter := converter.NewJockeyEntityConverter()
	list := aggregation_service.NewList(raceEntityConverter, jockeyEntityConverter, spreadSheetRepository)
	aggregation_usecaseList := aggregation_usecase.NewList(list)
	aggregation := controller.NewAggregation(aggregation_usecaseSummary, aggregation_usecaseTicketSummary, aggregation_usecaseList)
	return aggregation
}

func NewAnalysis() *controller.Analysis {
	analysisFilter := filter_service.NewAnalysisFilter()
	spreadSheetSummaryGateway := gateway.NewSpreadSheetSummaryGateway()
	spreadSheetTicketSummaryGateway := gateway.NewSpreadSheetTicketSummaryGateway()
	spreadSheetListGateway := gateway.NewSpreadSheetListGateway()
	spreadSheetAnalysisPlaceGateway := gateway.NewSpreadSheetAnalysisPlaceGateway()
	spreadSheetPredictionGateway := gateway.NewSpreadSheetPredictionGateway()
	spreadSheetRepository := infrastructure.NewSpreadSheetRepository(spreadSheetSummaryGateway, spreadSheetTicketSummaryGateway, spreadSheetListGateway, spreadSheetAnalysisPlaceGateway, spreadSheetPredictionGateway)
	place := analysis_service.NewPlace(analysisFilter, spreadSheetRepository)
	trio := analysis_service.NewTrio(analysisFilter)
	analysis := analysis_usecase.NewAnalysis(place, trio)
	controllerAnalysis := controller.NewAnalysis(analysis)
	return controllerAnalysis
}

func NewPrediction() *controller.Prediction {
	netKeibaGateway := gateway.NewNetKeibaGateway()
	oddsRepository := infrastructure.NewOddsRepository(netKeibaGateway)
	raceRepository := infrastructure.NewRaceRepository(netKeibaGateway)
	spreadSheetSummaryGateway := gateway.NewSpreadSheetSummaryGateway()
	spreadSheetTicketSummaryGateway := gateway.NewSpreadSheetTicketSummaryGateway()
	spreadSheetListGateway := gateway.NewSpreadSheetListGateway()
	spreadSheetAnalysisPlaceGateway := gateway.NewSpreadSheetAnalysisPlaceGateway()
	spreadSheetPredictionGateway := gateway.NewSpreadSheetPredictionGateway()
	spreadSheetRepository := infrastructure.NewSpreadSheetRepository(spreadSheetSummaryGateway, spreadSheetTicketSummaryGateway, spreadSheetListGateway, spreadSheetAnalysisPlaceGateway, spreadSheetPredictionGateway)
	predictionFilter := filter_service.NewPredictionFilter()
	odds := prediction_service.NewOdds(oddsRepository, raceRepository, spreadSheetRepository, predictionFilter)
	analysisFilter := filter_service.NewAnalysisFilter()
	place := analysis_service.NewPlace(analysisFilter, spreadSheetRepository)
	prediction := prediction_usecase.NewPrediction(odds, place)
	controllerPrediction := controller.NewPrediction(prediction)
	return controllerPrediction
}

// wire.go:

var MasterSet = wire.NewSet(master_usecase.NewMaster, master_service.NewTicket, master_service.NewRaceId, master_service.NewRace, master_service.NewJockey, master_service.NewPlaceOdds, master_service.NewTrioOdds, master_service.NewAnalysisMarker, master_service.NewPredictionMarker, master_service.NewBetNumberConverter, converter.NewRaceEntityConverter, converter.NewJockeyEntityConverter, converter.NewOddsEntityConverter, infrastructure.NewTicketRepository, infrastructure.NewRaceIdRepository, infrastructure.NewRaceRepository, infrastructure.NewJockeyRepository, infrastructure.NewOddsRepository, infrastructure.NewAnalysisMarkerRepository, infrastructure.NewPredictionMarkerRepository, gateway.NewNetKeibaGateway)

var AggregationSet = wire.NewSet(aggregation_usecase.NewSummary, aggregation_usecase.NewTicketSummary, aggregation_usecase.NewList, aggregation_service.NewSummary, aggregation_service.NewTicketSummary, aggregation_service.NewList, summary_service.NewTerm, summary_service.NewTicket, summary_service.NewClass, summary_service.NewCourseCategory, summary_service.NewDistanceCategory, summary_service.NewRaceCourse, infrastructure.NewSpreadSheetRepository, converter.NewRaceEntityConverter, converter.NewJockeyEntityConverter)

var AnalysisSet = wire.NewSet(analysis_usecase.NewAnalysis, analysis_service.NewPlace, analysis_service.NewTrio, filter_service.NewAnalysisFilter, infrastructure.NewSpreadSheetRepository)

var PredictionSet = wire.NewSet(prediction_usecase.NewPrediction, prediction_service.NewOdds, filter_service.NewPredictionFilter, infrastructure.NewOddsRepository, infrastructure.NewRaceRepository, gateway.NewNetKeibaGateway)

var SpreadSheetGatewaySet = wire.NewSet(gateway.NewSpreadSheetSummaryGateway, gateway.NewSpreadSheetTicketSummaryGateway, gateway.NewSpreadSheetListGateway, gateway.NewSpreadSheetAnalysisPlaceGateway, gateway.NewSpreadSheetPredictionGateway)
